title: GlideWall
description: Adaptive auto-updating slideshow for folders of images.
# GitHub Pages Jekyll config
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
# Relative logo path (site root is the docs folder)
logo: assets/glidewall-logo.svg
